module.exports = {
    port: 8181,
    nssSyncInterval: 6000,
    pages: [
      // SEO首页、首页、频道页、wifi万能钥匙首页
      require('./pages/wifiIndex'),
      require('./pages/lpdsIndex'),
      require('./pages/touchIndex'),
      require('./pages/newsChannel'),
      require('./pages/entChannel'),
      require('./pages/sportsChannel'),
      require('./pages/moneyChannel'),
      require('./pages/photoChannel'),
      require('./pages/autoChannel'),
      require('./pages/warChannel'),
      require('./pages/liveshowChannel'),
      require('./pages/videoChannel'),
      require('./pages/techChannel'),
      require('./pages/mobileChannel'),
      require('./pages/digiChannel'),
      require('./pages/localChannel'),
      require('./pages/dyChannel'),
      require('./pages/jokeChannel'),
      require('./pages/ladyChannel'),
      require('./pages/tieChannel'),
      require('./pages/gameChannel'),
      require('./pages/eduChannel'),
      require('./pages/openChannel'),
      require('./pages/jiankangChannel'),
      require('./pages/travelChannel'),
      require('./pages/babyChannel'),
      require('./pages/artChannel'),
      require('./pages/shuangchuangChannel'),
      require('./pages/airChannel'),
      require('./pages/caipiaoChannel'),
      require('./pages/exclusiveChannel'),
      require('./pages/jiuChannel'),
      require('./pages/neweraChannel'),
      require('./pages/wc2018Channel'),
      require('./pages/channel'),
      require('./pages/subChannel'),
      // 最终页
      require('./pages/article'),
      require('./pages/photoview'),
      require('./pages/special'),
      require('./pages/video'),
      require('./pages/mipArticle'),
      require('./pages/qqBrowserArticle'),
      require('./pages/baiduCambrianArticle'),
      require('./pages/ampArticle'),
      require('./pages/meiyouArticle'),
      require('./pages/zhwnlArticle'),
      require('./pages/zhwnlVideo'),
      require('./pages/wifiArticle'),
      require('./pages/bulletArticle'),
      require('./pages/soGouArticle'),
      require('./pages/huaweiArticle'),
      require('./pages/soGouVideo'),
      require('./pages/index'),
      require('./pages/weatherArticle'),
      // 适老化
      require('./pages/suitableAgeIndex'),
      require('./pages/suitableAgeArticle'),
      // require("./pages/mipVideo")
    ],
    // For dev use
    serviceApi: [
      require('./serviceApi/article'),
      require('./serviceApi/zhwnlArticle'),
      require('./serviceApi/photoview'),
      require('./serviceApi/special'),
      require('./serviceApi/video'),
      require('./serviceApi/mipArticle'),
      require('./serviceApi/index'),
      require('./serviceApi/channel'),
      require('./serviceApi/qqBrowserArticle'),
      require('./serviceApi/baiduCambrianArticle'),
      require('./serviceApi/meiyouArticle'),
      require('./serviceApi/ampArticle'),
    ],
    test:'GGGGGGGG'
  }
  